[project]
name = "qwen2-exercise"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "datasets>=4.3.0",
    "huggingface-hub>=0.36.0",
    "openai>=2.6.1",
    "requests>=2.32.5",
]
